name: stlgui
description: SummitTrackList app
version: 0.0.1+1
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  provider: ^6.0.3
  http: 0.13.4
  line_icons: ^2.0.1
  flutter_dotenv: ^5.0.2
  google_maps_flutter: ^2.1.5
  google_maps_flutter_web: ^0.3.2+2
  geolocator: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - .env
    - images/summit-tracks-live-2.png
    - assets/starting-point.png
